name: train-ai

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: sudo apt-get install -y build-essential libxi-dev libglu1-mesa-dev libglew-dev pkg-config
      - run: npm init -y
      - run: npm i gpu.js
      - run: npm i brain.js
      - run: node index.js
      - name: Commiting Changes
        run: |
          git add network_state.json
          git config --global user.name 'pawanpratapweb'
          git config --global user.email 'pawanpratapweb@users.noreply.github.com'
          git commit -am "Automated report"
          git push
